// Generated by Gradle task 'generateCountryNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryNameResolver_mi: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "BR", value = "Parahi", language = "mi")
      put(key = "CN", value = "Haina", language = "mi")
      put(key = "DE", value = "Tiamana", language = "mi")
      put(key = "FR", value = "Wīwī", language = "mi")
      put(key = "GB", value = "Hononga o Piritene", language = "mi")
      put(key = "IN", value = "Inia", language = "mi")
      put(key = "IT", value = "Itāria", language = "mi")
      put(key = "JP", value = "Hapani", language = "mi")
      put(key = "MK", value = "Makerōnia ki te Raki", language = "mi")
      put(key = "NZ", value = "Aotearoa", language = "mi")
      put(key = "RU", value = "Rūhia", language = "mi")
      put(key = "US", value = "Hononga o Amerika", language = "mi")
      put(key = "ZZ", value = "Rohe Tē Mōhiotia", language = "mi")
    }

