// Generated by Gradle task 'generateCountryNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryNameResolver_bem: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "ZM", value = "Zambia", language = "bem")
    }

