// Generated by Gradle task 'generateCountryNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryNameResolver_gv: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "GB", value = "Rywvaneth Unys", language = "gv")
      put(key = "IM", value = "Ellan Vannin", language = "gv")
    }

