// Generated by Gradle task 'generateCountryNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryNameResolver_rw: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "MK", value = "Masedoniya y’Amajyaruguru", language = "rw")
      put(key = "RW", value = "U Rwanda", language = "rw")
      put(key = "TO", value = "Tonga", language = "rw")
    }

