// Generated by Gradle task 'generateCountryNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryNameResolver_xh: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "MK", value = "uMntla Macedonia", language = "xh")
      put(key = "ZA", value = "eMzantsi Afrika", language = "xh")
    }

