// Generated by Gradle task 'generateCountryNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryNameResolver_nnh: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "CM", value = "Kàmalûm", language = "nnh")
    }

