// Generated by Gradle task 'generateCountryNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryNameResolver_om: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "BR", value = "Brazil", language = "om")
      put(key = "CN", value = "China", language = "om")
      put(key = "DE", value = "Germany", language = "om")
      put(key = "ET", value = "Itoophiyaa", language = "om")
      put(key = "FR", value = "France", language = "om")
      put(key = "GB", value = "United Kingdom", language = "om")
      put(key = "IN", value = "India", language = "om")
      put(key = "IT", value = "Italy", language = "om")
      put(key = "JP", value = "Japan", language = "om")
      put(key = "KE", value = "Keeniyaa", language = "om")
      put(key = "RU", value = "Russia", language = "om")
      put(key = "US", value = "United States", language = "om")
    }

