// Generated by Gradle task 'generateCountryNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryNameResolver_sat: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "BR", value = "ᱵᱨᱟᱡᱤᱞ", language = "sat")
      put(key = "CN", value = "ᱪᱤᱱ", language = "sat")
      put(key = "DE", value = "ᱡᱟᱨᱢᱟᱱᱤ", language = "sat")
      put(key = "FR", value = "ᱯᱷᱨᱟᱱᱥ", language = "sat")
      put(key = "GB", value = "ᱭᱩᱱᱤᱭᱴᱮᱰ ᱠᱤᱝᱰᱚᱢ", language = "sat")
      put(key = "IN", value = "ᱤᱱᱰᱤᱭᱟ", language = "sat")
      put(key = "IT", value = "ᱤᱴᱞᱤ", language = "sat")
      put(key = "JP", value = "ᱡᱟᱯᱟᱱ", language = "sat")
      put(key = "RU", value = "ᱨᱩᱥ", language = "sat")
      put(key = "US", value = "ᱭᱩᱱᱟᱭᱴᱮᱰ ᱮᱥᱴᱮᱴ", language = "sat")
      put(key = "ZZ", value = "ᱵᱟᱝᱩᱨᱩᱢ ᱴᱚᱴᱷᱟ", language = "sat")
    }

