// Generated by Gradle task 'generateCountryNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryNameResolver_kkj: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "CM", value = "Kamɛrun", language = "kkj")
    }

