// Generated by Gradle task 'generateCountryNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryNameResolver_vo: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "BR", value = "Brasilän", language = "vo")
      put(key = "CN", value = "Tsyinän", language = "vo")
      put(key = "DE", value = "Deutän", language = "vo")
      put(key = "ES", value = "Spanyän", language = "vo")
      put(key = "FR", value = "Fransän", language = "vo")
      put(key = "GB", value = "Regän Pebalöl", language = "vo")
      put(key = "GE", value = "Grusiyän", language = "vo")
      put(key = "GR", value = "Grikän", language = "vo")
      put(key = "IN", value = "Lindän", language = "vo")
      put(key = "IT", value = "Litaliyän", language = "vo")
      put(key = "JP", value = "Yapän", language = "vo")
      put(key = "MX", value = "Mäxikän", language = "vo")
      put(key = "NR", value = "Naureän", language = "vo")
      put(key = "PT", value = "Portugän", language = "vo")
      put(key = "PW", value = "Palauäns", language = "vo")
      put(key = "RU", value = "Rusän", language = "vo")
      put(key = "US", value = "Lamerikän", language = "vo")
    }

