// Generated by Gradle task 'generateCountryVariantNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryVariantNameResolver_ii: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "BR", value = "ꀠꑭ", language = "ii")
      put(key = "CN", value = "ꍏꇩ", language = "ii")
      put(key = "DE", value = "ꄓꇩ", language = "ii")
      put(key = "FR", value = "ꃔꇩ", language = "ii")
      put(key = "GB", value = "ꑱꇩ", language = "ii")
      put(key = "IN", value = "ꑴꄗ", language = "ii")
      put(key = "IT", value = "ꑴꄊꆺ", language = "ii")
      put(key = "JP", value = "ꏝꀪ", language = "ii")
      put(key = "RU", value = "ꊉꇆꌦ", language = "ii")
      put(key = "US", value = "ꂰꇩ", language = "ii")
      put(key = "ZZ", value = "ꃅꄷꅉꀋꐚꌠ", language = "ii")
    }

