// Generated by Gradle task 'generateCountryVariantNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryVariantNameResolver_lkt: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "001", value = "Makȟásitomni", language = "lkt")
      put(key = "002", value = "Hásapa Makȟáwita", language = "lkt")
      put(key = "019", value = "Khéya Wíta", language = "lkt")
      put(key = "142", value = "Hazíla Makȟáwita", language = "lkt")
      put(key = "150", value = "Wašíču Makȟáwita", language = "lkt")
      put(key = "CA", value = "Uŋčíyapi Makȟóčhe", language = "lkt")
      put(key = "CN", value = "Pȟečhókaŋhaŋska Makȟóčhe", language = "lkt")
      put(key = "DE", value = "Iyášiča Makȟóčhe", language = "lkt")
      put(key = "ES", value = "Spayólaȟče Makȟóčhe", language = "lkt")
      put(key = "JP", value = "Kisúŋla Makȟóčhe", language = "lkt")
      put(key = "MX", value = "Spayóla Makȟóčhe", language = "lkt")
      put(key = "US", value = "Mílahaŋska Tȟamákȟočhe", language = "lkt")
    }

