// Generated by Gradle task 'generateCountryVariantNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryVariantNameResolver_os: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "001", value = "Дуне", language = "os")
      put(key = "002", value = "Африкӕ", language = "os")
      put(key = "009", value = "Океани", language = "os")
      put(key = "019", value = "Америкӕ", language = "os")
      put(key = "142", value = "Ази", language = "os")
      put(key = "150", value = "Европӕ", language = "os")
      put(key = "BR", value = "Бразили", language = "os")
      put(key = "CN", value = "Китай", language = "os")
      put(key = "DE", value = "Герман", language = "os")
      put(key = "FR", value = "Франц", language = "os")
      put(key = "GB", value = "Стыр Британи", language = "os")
      put(key = "GE", value = "Гуырдзыстон", language = "os")
      put(key = "IN", value = "Инди", language = "os")
      put(key = "IT", value = "Итали", language = "os")
      put(key = "JP", value = "Япон", language = "os")
      put(key = "RU", value = "Уӕрӕсе", language = "os")
      put(key = "US", value = "АИШ", language = "os")
      put(key = "ZZ", value = "Нӕзонгӕ бӕстӕ", language = "os")
    }

