// Generated by Gradle task 'generateCountryVariantNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryVariantNameResolver_mni: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "BR", value = "ব্রাজিল", language = "mni")
      put(key = "CN", value = "চিনা", language = "mni")
      put(key = "DE", value = "জর্মনি", language = "mni")
      put(key = "FR", value = "ফ্রান্স", language = "mni")
      put(key = "GB", value = "য়ুনাইটেদ কিংদম", language = "mni")
      put(key = "IN", value = "ইন্দিয়া", language = "mni")
      put(key = "IT", value = "ইটালি", language = "mni")
      put(key = "JP", value = "জাপান", language = "mni")
      put(key = "RU", value = "রুসিয়া", language = "mni")
      put(key = "US", value = "য়ুনাইটেদ ষ্টেটস", language = "mni")
      put(key = "ZZ", value = "মশকখংদবা লমদম", language = "mni")
    }

