// Generated by Gradle task 'generateCountryVariantNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryVariantNameResolver_bem: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "ZM", value = "Zambia", language = "bem")
    }

