// Generated by Gradle task 'generateCountryVariantNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryVariantNameResolver_haw: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "AU", value = "Nūhōlani", language = "haw")
      put(key = "CA", value = "Kanakā", language = "haw")
      put(key = "CN", value = "Kina", language = "haw")
      put(key = "DE", value = "Kelemānia", language = "haw")
      put(key = "DK", value = "Kenemaka", language = "haw")
      put(key = "ES", value = "Kepania", language = "haw")
      put(key = "FR", value = "Palani", language = "haw")
      put(key = "GB", value = "Aupuni Mōʻī Hui Pū ʻIa", language = "haw")
      put(key = "GR", value = "Helene", language = "haw")
      put(key = "IE", value = "ʻIlelani", language = "haw")
      put(key = "IL", value = "ʻIseraʻela", language = "haw")
      put(key = "IN", value = "ʻĪnia", language = "haw")
      put(key = "IT", value = "ʻĪkālia", language = "haw")
      put(key = "JP", value = "Iāpana", language = "haw")
      put(key = "MX", value = "Mekiko", language = "haw")
      put(key = "NL", value = "Hōlani", language = "haw")
      put(key = "NZ", value = "Aotearoa", language = "haw")
      put(key = "PH", value = "ʻĀina Pilipino", language = "haw")
      put(key = "RU", value = "Lūkia", language = "haw")
      put(key = "US", value = "ʻAmelika Hui Pū ʻIa", language = "haw")
    }

