// Generated by Gradle task 'generateCountryVariantNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryVariantNameResolver_sah: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "001", value = "Аан дойду", language = "sah")
      put(key = "002", value = "Аапырыка", language = "sah")
      put(key = "003", value = "Хотугу Эмиэрикэ", language = "sah")
      put(key = "005", value = "Соҕуруу Эмиэрикэ", language = "sah")
      put(key = "BR", value = "Бразилия", language = "sah")
      put(key = "CA", value = "Канаада", language = "sah")
      put(key = "CL", value = "Чиили", language = "sah")
      put(key = "CN", value = "Кытай", language = "sah")
      put(key = "CU", value = "Кууба", language = "sah")
      put(key = "EE", value = "Эстония", language = "sah")
      put(key = "FI", value = "Финляндия", language = "sah")
      put(key = "GB", value = "Улуу Британия", language = "sah")
      put(key = "IE", value = "Ирландия", language = "sah")
      put(key = "IM", value = "Мэн арыы", language = "sah")
      put(key = "IS", value = "Исландия", language = "sah")
      put(key = "JM", value = "Дьамаайка", language = "sah")
      put(key = "LT", value = "Литва", language = "sah")
      put(key = "LV", value = "Латвия", language = "sah")
      put(key = "LY", value = "Лиибийэ", language = "sah")
      put(key = "MX", value = "Миэксикэ", language = "sah")
      put(key = "NO", value = "Норвегия", language = "sah")
      put(key = "RU", value = "Арассыыйа", language = "sah")
      put(key = "SD", value = "Судаан", language = "sah")
      put(key = "SE", value = "Швеция", language = "sah")
      put(key = "US", value = "Америка Холбоһуктаах Штааттара", language = "sah")
    }

