// Generated by Gradle task 'generateCountryVariantNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryVariantNameResolver_dua: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "CM", value = "Cameroun", language = "dua")
    }

