// Generated by Gradle task 'generateCountryVariantNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryVariantNameResolver_kw: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "001", value = "An Bys", language = "kw")
      put(key = "002", value = "Afrika", language = "kw")
      put(key = "003", value = "Amerika Gledh", language = "kw")
      put(key = "019", value = "An Amerikas", language = "kw")
      put(key = "142", value = "Asi", language = "kw")
      put(key = "150", value = "Europa", language = "kw")
      put(key = "BR", value = "Brasil", language = "kw")
      put(key = "CN", value = "China", language = "kw")
      put(key = "DE", value = "Almayn", language = "kw")
      put(key = "EU", value = "Unyans Europek", language = "kw")
      put(key = "FR", value = "Pow Frenk", language = "kw")
      put(key = "GB", value = "Rywvaneth Unys", language = "kw")
      put(key = "IN", value = "Eynda", language = "kw")
      put(key = "IT", value = "Itali", language = "kw")
      put(key = "JP", value = "Japan", language = "kw")
      put(key = "RU", value = "Russi", language = "kw")
      put(key = "UN", value = "Kenedhlow Unys", language = "kw")
      put(key = "US", value = "Statys Unys", language = "kw")
    }

