// Generated by Gradle task 'generateCountryShortNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryShortNameResolver_mai: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "BR", value = "ब्राज़ील", language = "mai")
      put(key = "CN", value = "चीन", language = "mai")
      put(key = "DE", value = "जर्मनी", language = "mai")
      put(key = "FR", value = "फ़्रांस", language = "mai")
      put(key = "GB", value = "यूनाइटेड किंगडम", language = "mai")
      put(key = "IN", value = "भारत", language = "mai")
      put(key = "IT", value = "इटली", language = "mai")
      put(key = "JP", value = "जापान", language = "mai")
      put(key = "RU", value = "रूस", language = "mai")
      put(key = "US", value = "संयुक्त राज्य", language = "mai")
      put(key = "ZZ", value = "अज्ञात क्षेत्र", language = "mai")
    }

