// Generated by Gradle task 'generateCountryShortNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryShortNameResolver_cu: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "AU", value = "А҆ѵстралі́ѧ", language = "cu")
      put(key = "BR", value = "бразі́лїа", language = "cu")
      put(key = "BY", value = "бѣ́лаѧ рꙋ́сь", language = "cu")
      put(key = "CA", value = "Кана́да", language = "cu")
      put(key = "CN", value = "хи́нскаѧ страна̀", language = "cu")
      put(key = "DE", value = "герма́нїа", language = "cu")
      put(key = "DK", value = "Дані́ѧ", language = "cu")
      put(key = "FR", value = "га́ллїа", language = "cu")
      put(key = "GB", value = "Вели́каѧ брїта́нїа", language = "cu")
      put(key = "IN", value = "і҆́ндїа", language = "cu")
      put(key = "IT", value = "і҆та́лїа", language = "cu")
      put(key = "JP", value = "ꙗ҆пѡ́нїа", language = "cu")
      put(key = "KG", value = "кирги́зїа", language = "cu")
      put(key = "KZ", value = "казахста́нъ", language = "cu")
      put(key = "MX", value = "Ме́ѯїко", language = "cu")
      put(key = "RU", value = "рѡссі́а", language = "cu")
      put(key = "UA", value = "ᲂу҆краи́на", language = "cu")
      put(key = "US", value = "а҆мерїка̑нскїѧ соединє́нныѧ держа̑вы", language = "cu")
      put(key = "ZZ", value = "невѣ́домаѧ страна̀", language = "cu")
    }

