// Generated by Gradle task 'generateCountryShortNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryShortNameResolver_lrc: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "001", value = "دونیا", language = "lrc")
      put(key = "002", value = "ئفریقا", language = "lrc")
      put(key = "003", value = "ئمریکا شومالی", language = "lrc")
      put(key = "005", value = "ئمریکا ھارگە", language = "lrc")
      put(key = "009", value = "ھوم پئڤأند جأھوٙن آڤ", language = "lrc")
      put(key = "013", value = "مینجا ئمریکا", language = "lrc")
      put(key = "019", value = "ئمریکا", language = "lrc")
      put(key = "021", value = "ئمریکا ڤارو", language = "lrc")
      put(key = "029", value = "کارائیب", language = "lrc")
      put(key = "142", value = "آسیا", language = "lrc")
      put(key = "150", value = "ئوروٙپا", language = "lrc")
      put(key = "419", value = "ئمریکا لاتین", language = "lrc")
      put(key = "BR", value = "بئرئزیل", language = "lrc")
      put(key = "CN", value = "چین", language = "lrc")
      put(key = "DE", value = "آلمان", language = "lrc")
      put(key = "FR", value = "فأرانسە", language = "lrc")
      put(key = "GB", value = "بیریتانیا گأپ", language = "lrc")
      put(key = "IN", value = "ھئن", language = "lrc")
      put(key = "IT", value = "ئیتالیا", language = "lrc")
      put(key = "JP", value = "جاپوٙن", language = "lrc")
      put(key = "RU", value = "روٙسیە", language = "lrc")
      put(key = "US", value = "ڤولاتیا یأکاگئرتە", language = "lrc")
      put(key = "ZZ", value = "راساگە نادیار", language = "lrc")
    }

