// Generated by Gradle task 'generateCountryShortNameResolver'. Do not edit manually.
package io.fluidsonic.i18n.data

import io.fluidsonic.locale.LocalizedValueResolver
import kotlin.String

internal val countryShortNameResolver_su: LocalizedValueResolver<String, String> =
    LocalizedValueResolver.buildMap {
      put(key = "BR", value = "Brasil", language = "su")
      put(key = "CN", value = "Tiongkok", language = "su")
      put(key = "DE", value = "Jérman", language = "su")
      put(key = "FR", value = "Prancis", language = "su")
      put(key = "GB", value = "Inggris Raya", language = "su")
      put(key = "IN", value = "India", language = "su")
      put(key = "IT", value = "Italia", language = "su")
      put(key = "JP", value = "Jepang", language = "su")
      put(key = "RU", value = "Rusia", language = "su")
      put(key = "US", value = "Amérika Sarikat", language = "su")
      put(key = "ZZ", value = "Wilayah Teu Dipikaterang", language = "su")
    }

