name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  packages: read

jobs:
  js:
    name: JS
    runs-on: ubuntu-latest
    env:
      GITHUB_PACKAGES_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew jsTest

  jvm:
    name: JVM
    runs-on: ubuntu-latest
    env:
      GITHUB_PACKAGES_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew jvmTest
